'use client';
import {useEffect,useRef,useState} from 'react';
// @ts-ignore
import {World,RADII} from './physics.mjs';
const colors=['#91dfd1','#78c8ee','#96a4fc','#c69bf3','#f494ba','#ffac89','#f4cf72','#c5df74','#7ed2ab','#6ba7ef','#e8dfb9'];
export default function Game(){
 const canvas=useRef<HTMLCanvasElement>(null),world=useRef<any>(null),nextRef=useRef(0),pointer=useRef({x:400,y:130,visible:false});
 const [stats,setStats]=useState({score:0,best:0,max:0});
 const records=useRef({best:0,max:0});
 useEffect(()=>{const c=canvas.current!,ctx=c.getContext('2d')!;world.current=new World(800,650);
 const readRecords=()=>{try{const data=JSON.parse(localStorage.getItem('merge11-records')||'{}');return {best:Number.isSafeInteger(data.best)&&data.best>=0?data.best:0,max:Number.isInteger(data.max)&&data.max>=0&&data.max<=11?data.max:0};}catch{return {best:0,max:0};}};
 records.current=readRecords();setStats({score:0,...records.current});
 const syncRecords=()=>{const saved=readRecords(),w=world.current;const best=Math.max(saved.best,records.current.best,w.score),max=Math.max(saved.max,records.current.max,w.max+1);records.current={best,max};if(saved.best!==best||saved.max!==max){try{localStorage.setItem('merge11-records',JSON.stringify(records.current));}catch{}}setStats({score:w.score,best,max});};
 const onStorage=(event:StorageEvent)=>{if(event.key==='merge11-records')syncRecords();};window.addEventListener('storage',onStorage);window.addEventListener('pagehide',syncRecords);
 let frame=0,previous=0,acc=0,lastUI=0;
 const draw=(time:number)=>{if(!previous)previous=time;acc+=Math.min((time-previous)/1000,.05);previous=time;const w=world.current;while(acc>=1/120){w.step();acc-=1/120;}ctx.clearRect(0,0,800,650);
 ctx.fillStyle='#29343c';for(let x=20;x<800;x+=30)for(let y=20;y<650;y+=30){ctx.beginPath();ctx.arc(x,y,.8,0,Math.PI*2);ctx.fill();}
 for(const b of w.balls){const t=Math.min(1,(b.mergeAge??1)/.14),ease=1-Math.pow(1-t,3),scale=.72+.28*ease;ctx.save();ctx.translate(b.x,b.y);ctx.scale(scale,scale);ctx.translate(-b.x,-b.y);ctx.beginPath();ctx.arc(b.x,b.y,b.r-1,0,Math.PI*2);ctx.fillStyle=colors[b.level];ctx.fill();ctx.strokeStyle='#ffffff55';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#18272e';ctx.font=`600 ${Math.max(12,b.r*.5)}px ui-monospace,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(b.level+1).padStart(2,'0'),b.x,b.y);ctx.restore();if(t<1){ctx.beginPath();ctx.arc(b.x,b.y,b.r*(1+.2*t),0,Math.PI*2);ctx.strokeStyle=colors[b.level];ctx.globalAlpha=(1-t)*.45;ctx.lineWidth=2*(1-t);ctx.stroke();ctx.globalAlpha=1;}}
 if(pointer.current.visible){const r=RADII[nextRef.current],x=Math.max(r,Math.min(800-r,pointer.current.x)),y=Math.max(r,Math.min(650-r,pointer.current.y));ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=colors[nextRef.current]+'20';ctx.fill();ctx.strokeStyle=colors[nextRef.current]+'99';ctx.setLineDash([4,5]);ctx.stroke();ctx.setLineDash([]);}
 if(time-lastUI>150){syncRecords();lastUI=time;}frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>{syncRecords();cancelAnimationFrame(frame);window.removeEventListener('storage',onStorage);window.removeEventListener('pagehide',syncRecords);};},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'drop_ball',description:'在游戏区域指定空位生成下一颗球，坐标范围 x 0–800、y 0–650。',inputSchema:{type:'object',properties:{x:{type:'number',minimum:0,maximum:800},y:{type:'number',minimum:0,maximum:650}},required:['x','y'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||!Number.isFinite(input.x)||!Number.isFinite(input.y)||input.x<0||input.x>800||input.y<0||input.y>650)throw new Error('无效坐标');const before=world.current.balls.length;drop(input.x,input.y);return {created:world.current.balls.length>before,count:world.current.balls.length};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 function drop(x:number,y:number){if(world.current?.spawn(x,y,nextRef.current))nextRef.current=Math.floor(Math.random()*5);}
 return <main><header className="scoreboard" aria-label="游戏分数"><div><span>总分数</span><strong>{stats.score.toLocaleString()}</strong></div><div><span>历史最高</span><strong>{stats.best.toLocaleString()}</strong></div><div><span>历史最大</span><strong>{stats.max?`${stats.max} 号`:'—'}</strong></div></header><div className="basket"><canvas ref={canvas} width={800} height={650} tabIndex={0} aria-label="合成游戏区域，点击空位生成球。方向键移动落点，空格或回车生成。" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-r.left)*800/r.width,y:(e.clientY-r.top)*650/r.height,visible:true};}} onPointerLeave={()=>{pointer.current.visible=false;}} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();drop((e.clientX-r.left)*800/r.width,(e.clientY-r.top)*650/r.height);}} onKeyDown={e=>{const p=pointer.current;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter'].includes(e.key)){e.preventDefault();p.visible=true;if(e.key==='ArrowLeft')p.x=Math.max(0,p.x-20);if(e.key==='ArrowRight')p.x=Math.min(800,p.x+20);if(e.key==='ArrowUp')p.y=Math.max(0,p.y-20);if(e.key==='ArrowDown')p.y=Math.min(650,p.y+20);if(e.key===' '||e.key==='Enter')drop(p.x,p.y);}}}/></div></main>;
}
